### ISSUE TITLE
Add pages

### ISSUE THREAD

**Issue by 1fabunicorn** [ideahackers/ideahack.club#3]
@SirTangent 

- `/contact`, we may just want a blurb with a contact@ideahackers.club email, or an actual submit form. Its up for debate. 
- `/meet-us`, I changed this from your commits. Its confusing as you had about and learn about us us on the site, so I cleared it up. 
- `/info`, we will write something up describing the club. I do think you are better at writing then me though!

**Comment by SirTangent** [comment]
- ```/contact```, if we are going to make it a page, we should create a contact form with the minimum of name, email, and message (<textarea>) inputs.
- ```/meet-us```, I think this should all be combined into one ```/aboutus``` page since showing teams would only consist of one div. In fact, the learn more page ```/info``` would also combine I believe. We can talk about the layout.
- ```/events```, could be a grid of cards that are fetched from the DB and could be filtered in different ways. There is functionality that lets you filter db documents in mongoose.

**Comment by 1fabunicorn** [comment]
>  - [x]   `/contact`, if we are going to make it a page, we should create a contact form with the minimum of name, email, and message (<textarea>) inputs.


> - [x]    * `/meet-us`, I think this should all be combined into one `/aboutus` page since showing teams would only consist of one div. In fact, the learn more page `/info` would also combine I believe. We can talk about the layout.
>  **NOTES: Information about the club**
>  **Blurbs with picture of us**

> - [x]  `/events`, could be a grid of cards that are fetched from the DB and could be filtered in different ways. There is functionality that lets you filter db documents in mongoose.
> **Create .handlebars file with the div and everything, that will be populated by the backend (me)**

**Comment by 1fabunicorn** [comment]
@SirTangent Bump as I just remembered this and knowing you, you prob forgot as well
